# fly.toml app configuration file generated for summer-river-3601 on 2023-07-21T22:49:49-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "summer-river-3601"
primary_region = "scl"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  PORT = "8080" # add this

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8080 
  processes = ["app"]

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[build]
  [build.args]
    NODE_VERSION = "16.13.2"

[[services.http_checks]]
  interval = 10000
  grace_period = "5s"
  method = "get"
  path = "/"
  protocol = "http"
  restart_limit = 0
  timeout = 2000
  tls_skip_verify = false
  [services.http_checks.headers]